// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: v1/ampb/rpc_create_anime_movie_data.proto

package ampbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAnimeMovieDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ServerID int64                     `protobuf:"varint,1,opt,name=serverID,proto3" json:"serverID,omitempty"`
	Sub      *AnimeMovieSubDataRequest `protobuf:"bytes,2,opt,name=sub,proto3" json:"sub,omitempty"`
	Dub      *AnimeMovieDubDataRequest `protobuf:"bytes,3,opt,name=dub,proto3" json:"dub,omitempty"`
}

func (x *CreateAnimeMovieDataRequest) Reset() {
	*x = CreateAnimeMovieDataRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ampb_rpc_create_anime_movie_data_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAnimeMovieDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnimeMovieDataRequest) ProtoMessage() {}

func (x *CreateAnimeMovieDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ampb_rpc_create_anime_movie_data_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnimeMovieDataRequest.ProtoReflect.Descriptor instead.
func (*CreateAnimeMovieDataRequest) Descriptor() ([]byte, []int) {
	return file_v1_ampb_rpc_create_anime_movie_data_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAnimeMovieDataRequest) GetServerID() int64 {
	if x != nil {
		return x.ServerID
	}
	return 0
}

func (x *CreateAnimeMovieDataRequest) GetSub() *AnimeMovieSubDataRequest {
	if x != nil {
		return x.Sub
	}
	return nil
}

func (x *CreateAnimeMovieDataRequest) GetDub() *AnimeMovieDubDataRequest {
	if x != nil {
		return x.Dub
	}
	return nil
}

type CreateAnimeMovieDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimeMovie *AnimeMovieResponse        `protobuf:"bytes,1,opt,name=animeMovie,proto3" json:"animeMovie,omitempty"`
	Sub        *AnimeMovieSubDataResponse `protobuf:"bytes,2,opt,name=sub,proto3" json:"sub,omitempty"`
	Dub        *AnimeMovieDubDataResponse `protobuf:"bytes,3,opt,name=dub,proto3" json:"dub,omitempty"`
}

func (x *CreateAnimeMovieDataResponse) Reset() {
	*x = CreateAnimeMovieDataResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_ampb_rpc_create_anime_movie_data_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAnimeMovieDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnimeMovieDataResponse) ProtoMessage() {}

func (x *CreateAnimeMovieDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_ampb_rpc_create_anime_movie_data_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnimeMovieDataResponse.ProtoReflect.Descriptor instead.
func (*CreateAnimeMovieDataResponse) Descriptor() ([]byte, []int) {
	return file_v1_ampb_rpc_create_anime_movie_data_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAnimeMovieDataResponse) GetAnimeMovie() *AnimeMovieResponse {
	if x != nil {
		return x.AnimeMovie
	}
	return nil
}

func (x *CreateAnimeMovieDataResponse) GetSub() *AnimeMovieSubDataResponse {
	if x != nil {
		return x.Sub
	}
	return nil
}

func (x *CreateAnimeMovieDataResponse) GetDub() *AnimeMovieDubDataResponse {
	if x != nil {
		return x.Dub
	}
	return nil
}

var File_v1_ampb_rpc_create_anime_movie_data_proto protoreflect.FileDescriptor

var file_v1_ampb_rpc_create_anime_movie_data_proto_rawDesc = []byte{
	0x0a, 0x29, 0x76, 0x31, 0x2f, 0x61, 0x6d, 0x70, 0x62, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x5f, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x6f, 0x76, 0x69, 0x65,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x76, 0x31, 0x2e,
	0x61, 0x6d, 0x70, 0x62, 0x76, 0x31, 0x1a, 0x19, 0x76, 0x31, 0x2f, 0x61, 0x6d, 0x70, 0x62, 0x2f,
	0x61, 0x6e, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x14, 0x76, 0x31, 0x2f, 0x61, 0x6d, 0x70, 0x62, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa7, 0x01, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x49, 0x44, 0x12, 0x35, 0x0a, 0x03, 0x73, 0x75, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x23, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x6d, 0x70, 0x62, 0x76, 0x31, 0x2e, 0x41, 0x6e, 0x69,
	0x6d, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x53, 0x75, 0x62, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x73, 0x75, 0x62, 0x12, 0x35, 0x0a, 0x03, 0x64, 0x75,
	0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x6d, 0x70,
	0x62, 0x76, 0x31, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x44, 0x75,
	0x62, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x03, 0x64, 0x75,
	0x62, 0x22, 0xcd, 0x01, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d,
	0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0a, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x6d, 0x70, 0x62,
	0x76, 0x31, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0a, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x4d, 0x6f, 0x76, 0x69,
	0x65, 0x12, 0x36, 0x0a, 0x03, 0x73, 0x75, 0x62, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24,
	0x2e, 0x76, 0x31, 0x2e, 0x61, 0x6d, 0x70, 0x62, 0x76, 0x31, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x65,
	0x4d, 0x6f, 0x76, 0x69, 0x65, 0x53, 0x75, 0x62, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x52, 0x03, 0x73, 0x75, 0x62, 0x12, 0x36, 0x0a, 0x03, 0x64, 0x75, 0x62,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x76, 0x31, 0x2e, 0x61, 0x6d, 0x70, 0x62,
	0x76, 0x31, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x44, 0x75, 0x62,
	0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x03, 0x64, 0x75,
	0x62, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x64, 0x6a, 0x2d, 0x79, 0x61, 0x63, 0x69, 0x6e, 0x65, 0x2d, 0x66, 0x6c, 0x75, 0x74, 0x74, 0x65,
	0x72, 0x2f, 0x67, 0x6f, 0x6a, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x6d, 0x70,
	0x62, 0x3b, 0x61, 0x6d, 0x70, 0x62, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_ampb_rpc_create_anime_movie_data_proto_rawDescOnce sync.Once
	file_v1_ampb_rpc_create_anime_movie_data_proto_rawDescData = file_v1_ampb_rpc_create_anime_movie_data_proto_rawDesc
)

func file_v1_ampb_rpc_create_anime_movie_data_proto_rawDescGZIP() []byte {
	file_v1_ampb_rpc_create_anime_movie_data_proto_rawDescOnce.Do(func() {
		file_v1_ampb_rpc_create_anime_movie_data_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_ampb_rpc_create_anime_movie_data_proto_rawDescData)
	})
	return file_v1_ampb_rpc_create_anime_movie_data_proto_rawDescData
}

var file_v1_ampb_rpc_create_anime_movie_data_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_ampb_rpc_create_anime_movie_data_proto_goTypes = []interface{}{
	(*CreateAnimeMovieDataRequest)(nil),  // 0: v1.ampbv1.CreateAnimeMovieDataRequest
	(*CreateAnimeMovieDataResponse)(nil), // 1: v1.ampbv1.CreateAnimeMovieDataResponse
	(*AnimeMovieSubDataRequest)(nil),     // 2: v1.ampbv1.AnimeMovieSubDataRequest
	(*AnimeMovieDubDataRequest)(nil),     // 3: v1.ampbv1.AnimeMovieDubDataRequest
	(*AnimeMovieResponse)(nil),           // 4: v1.ampbv1.AnimeMovieResponse
	(*AnimeMovieSubDataResponse)(nil),    // 5: v1.ampbv1.AnimeMovieSubDataResponse
	(*AnimeMovieDubDataResponse)(nil),    // 6: v1.ampbv1.AnimeMovieDubDataResponse
}
var file_v1_ampb_rpc_create_anime_movie_data_proto_depIdxs = []int32{
	2, // 0: v1.ampbv1.CreateAnimeMovieDataRequest.sub:type_name -> v1.ampbv1.AnimeMovieSubDataRequest
	3, // 1: v1.ampbv1.CreateAnimeMovieDataRequest.dub:type_name -> v1.ampbv1.AnimeMovieDubDataRequest
	4, // 2: v1.ampbv1.CreateAnimeMovieDataResponse.animeMovie:type_name -> v1.ampbv1.AnimeMovieResponse
	5, // 3: v1.ampbv1.CreateAnimeMovieDataResponse.sub:type_name -> v1.ampbv1.AnimeMovieSubDataResponse
	6, // 4: v1.ampbv1.CreateAnimeMovieDataResponse.dub:type_name -> v1.ampbv1.AnimeMovieDubDataResponse
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_v1_ampb_rpc_create_anime_movie_data_proto_init() }
func file_v1_ampb_rpc_create_anime_movie_data_proto_init() {
	if File_v1_ampb_rpc_create_anime_movie_data_proto != nil {
		return
	}
	file_v1_ampb_anime_movie_proto_init()
	file_v1_ampb_server_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_v1_ampb_rpc_create_anime_movie_data_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAnimeMovieDataRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_ampb_rpc_create_anime_movie_data_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAnimeMovieDataResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_ampb_rpc_create_anime_movie_data_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_ampb_rpc_create_anime_movie_data_proto_goTypes,
		DependencyIndexes: file_v1_ampb_rpc_create_anime_movie_data_proto_depIdxs,
		MessageInfos:      file_v1_ampb_rpc_create_anime_movie_data_proto_msgTypes,
	}.Build()
	File_v1_ampb_rpc_create_anime_movie_data_proto = out.File
	file_v1_ampb_rpc_create_anime_movie_data_proto_rawDesc = nil
	file_v1_ampb_rpc_create_anime_movie_data_proto_goTypes = nil
	file_v1_ampb_rpc_create_anime_movie_data_proto_depIdxs = nil
}
