# Migrate
FROM golang:1.21.5-alpine3.19
WORKDIR /gojo
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest
COPY db/migration ./db/migration
ENTRYPOINT ["sh", "-c"]
CMD ["migrate -path db/migration -database $DB_SOURCE -verbose up"]