// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: v1/apb/anime_trailer.proto

package apbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnimeTrailerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsOfficial bool   `protobuf:"varint,1,opt,name=isOfficial,proto3" json:"isOfficial,omitempty"`
	HostName   string `protobuf:"bytes,2,opt,name=hostName,proto3" json:"hostName,omitempty"`
	HostKey    string `protobuf:"bytes,3,opt,name=hostKey,proto3" json:"hostKey,omitempty"`
}

func (x *AnimeTrailerRequest) Reset() {
	*x = AnimeTrailerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_apb_anime_trailer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnimeTrailerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeTrailerRequest) ProtoMessage() {}

func (x *AnimeTrailerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_apb_anime_trailer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeTrailerRequest.ProtoReflect.Descriptor instead.
func (*AnimeTrailerRequest) Descriptor() ([]byte, []int) {
	return file_v1_apb_anime_trailer_proto_rawDescGZIP(), []int{0}
}

func (x *AnimeTrailerRequest) GetIsOfficial() bool {
	if x != nil {
		return x.IsOfficial
	}
	return false
}

func (x *AnimeTrailerRequest) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *AnimeTrailerRequest) GetHostKey() string {
	if x != nil {
		return x.HostKey
	}
	return ""
}

type AnimeTrailerResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID         int64                  `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	IsOfficial bool                   `protobuf:"varint,2,opt,name=isOfficial,proto3" json:"isOfficial,omitempty"`
	HostName   string                 `protobuf:"bytes,3,opt,name=hostName,proto3" json:"hostName,omitempty"`
	HostKey    string                 `protobuf:"bytes,4,opt,name=hostKey,proto3" json:"hostKey,omitempty"`
	CreatedAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=createdAt,proto3" json:"createdAt,omitempty"`
}

func (x *AnimeTrailerResponse) Reset() {
	*x = AnimeTrailerResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_apb_anime_trailer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnimeTrailerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimeTrailerResponse) ProtoMessage() {}

func (x *AnimeTrailerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_apb_anime_trailer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimeTrailerResponse.ProtoReflect.Descriptor instead.
func (*AnimeTrailerResponse) Descriptor() ([]byte, []int) {
	return file_v1_apb_anime_trailer_proto_rawDescGZIP(), []int{1}
}

func (x *AnimeTrailerResponse) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

func (x *AnimeTrailerResponse) GetIsOfficial() bool {
	if x != nil {
		return x.IsOfficial
	}
	return false
}

func (x *AnimeTrailerResponse) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *AnimeTrailerResponse) GetHostKey() string {
	if x != nil {
		return x.HostKey
	}
	return ""
}

func (x *AnimeTrailerResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_v1_apb_anime_trailer_proto protoreflect.FileDescriptor

var file_v1_apb_anime_trailer_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x62, 0x2f, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x5f, 0x74,
	0x72, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x76, 0x31,
	0x2e, 0x61, 0x70, 0x62, 0x76, 0x31, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x13, 0x41, 0x6e, 0x69, 0x6d, 0x65,
	0x54, 0x72, 0x61, 0x69, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x69, 0x73, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x12, 0x1a,
	0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f,
	0x73, 0x74, 0x4b, 0x65, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x6f, 0x73,
	0x74, 0x4b, 0x65, 0x79, 0x22, 0xb6, 0x01, 0x0a, 0x14, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x54, 0x72,
	0x61, 0x69, 0x6c, 0x65, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a,
	0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x44, 0x12, 0x1e, 0x0a,
	0x0a, 0x69, 0x73, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x0a, 0x69, 0x73, 0x4f, 0x66, 0x66, 0x69, 0x63, 0x69, 0x61, 0x6c, 0x12, 0x1a, 0x0a,
	0x08, 0x68, 0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x68, 0x6f, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x6f, 0x73,
	0x74, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x68, 0x6f, 0x73, 0x74,
	0x4b, 0x65, 0x79, 0x12, 0x38, 0x0a, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x42, 0x33, 0x5a,
	0x31, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6a, 0x2d, 0x79,
	0x61, 0x63, 0x69, 0x6e, 0x65, 0x2d, 0x66, 0x6c, 0x75, 0x74, 0x74, 0x65, 0x72, 0x2f, 0x67, 0x6f,
	0x6a, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x70, 0x62, 0x3b, 0x61, 0x70, 0x62,
	0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_apb_anime_trailer_proto_rawDescOnce sync.Once
	file_v1_apb_anime_trailer_proto_rawDescData = file_v1_apb_anime_trailer_proto_rawDesc
)

func file_v1_apb_anime_trailer_proto_rawDescGZIP() []byte {
	file_v1_apb_anime_trailer_proto_rawDescOnce.Do(func() {
		file_v1_apb_anime_trailer_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_apb_anime_trailer_proto_rawDescData)
	})
	return file_v1_apb_anime_trailer_proto_rawDescData
}

var file_v1_apb_anime_trailer_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_apb_anime_trailer_proto_goTypes = []interface{}{
	(*AnimeTrailerRequest)(nil),   // 0: v1.apbv1.AnimeTrailerRequest
	(*AnimeTrailerResponse)(nil),  // 1: v1.apbv1.AnimeTrailerResponse
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_v1_apb_anime_trailer_proto_depIdxs = []int32{
	2, // 0: v1.apbv1.AnimeTrailerResponse.createdAt:type_name -> google.protobuf.Timestamp
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_apb_anime_trailer_proto_init() }
func file_v1_apb_anime_trailer_proto_init() {
	if File_v1_apb_anime_trailer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_v1_apb_anime_trailer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnimeTrailerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_apb_anime_trailer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnimeTrailerResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_apb_anime_trailer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_apb_anime_trailer_proto_goTypes,
		DependencyIndexes: file_v1_apb_anime_trailer_proto_depIdxs,
		MessageInfos:      file_v1_apb_anime_trailer_proto_msgTypes,
	}.Build()
	File_v1_apb_anime_trailer_proto = out.File
	file_v1_apb_anime_trailer_proto_rawDesc = nil
	file_v1_apb_anime_trailer_proto_goTypes = nil
	file_v1_apb_anime_trailer_proto_depIdxs = nil
}
