-- SQL dump generated using DBML (dbml-lang.org)
-- Database: PostgreSQL
-- Generated at: 2023-10-11T11:36:02.649Z

CREATE TABLE "anime_movie" (
  "id" BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  "original_title" varchar NOT NULL,
  "aired" timestamptz NOT NULL,
  "release_year" integer NOT NULL,
  "duration" interval NOT NULL DEFAULT ('00h 00m 00s'),
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "studios" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "studio_name" varchar UNIQUE NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "anime_studio" (
  "id" BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  "anime_id" bigserial NOT NULL,
  "studio_id" integer
);

CREATE TABLE "genres" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "genre_name" varchar UNIQUE NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "anime_genre" (
  "id" BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  "anime_id" bigserial NOT NULL,
  "genre_id" integer
);

CREATE TABLE "languages" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY UNIQUE PRIMARY KEY NOT NULL,
  "language_code" varchar UNIQUE NOT NULL,
  "language_name" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE TABLE "anime_metas" (
  "id" BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  "anime_id" bigserial NOT NULL,
  "language_id" integer NOT NULL,
  "meta_id" bigserial NOT NULL
);

CREATE TABLE "metas" (
  "id" BIGSERIAL UNIQUE PRIMARY KEY NOT NULL,
  "title" varchar NOT NULL,
  "overview" varchar NOT NULL,
  "created_at" timestamptz NOT NULL DEFAULT (now())
);

CREATE INDEX ON "anime_movie" ("id");

CREATE INDEX ON "anime_movie" ("original_title");

CREATE INDEX ON "anime_movie" ("release_year");

CREATE UNIQUE INDEX ON "anime_movie" ("original_title", "duration", "aired");

CREATE INDEX ON "studios" ("id");

CREATE INDEX ON "studios" ("studio_name");

CREATE INDEX ON "anime_studio" ("anime_id");

CREATE INDEX ON "anime_studio" ("studio_id");

CREATE INDEX ON "genres" ("id");

CREATE INDEX ON "genres" ("genre_name");

CREATE INDEX ON "anime_genre" ("anime_id");

CREATE INDEX ON "anime_genre" ("genre_id");

CREATE INDEX ON "languages" ("id");

CREATE INDEX ON "languages" ("language_code");

CREATE INDEX ON "anime_metas" ("id");

CREATE UNIQUE INDEX ON "anime_metas" ("anime_id", "language_id");

CREATE INDEX ON "metas" ("id");

CREATE INDEX ON "metas" ("title");

ALTER TABLE "anime_studio" ADD FOREIGN KEY ("studio_id") REFERENCES "studios" ("id");

ALTER TABLE "anime_genre" ADD FOREIGN KEY ("genre_id") REFERENCES "genres" ("id");

ALTER TABLE "anime_metas" ADD FOREIGN KEY ("anime_id") REFERENCES "anime_movie" ("id") ON DELETE CASCADE;

ALTER TABLE "anime_studio" ADD FOREIGN KEY ("anime_id") REFERENCES "anime_movie" ("id") ON DELETE CASCADE;

ALTER TABLE "anime_genre" ADD FOREIGN KEY ("anime_id") REFERENCES "anime_movie" ("id") ON DELETE CASCADE;

ALTER TABLE "anime_metas" ADD FOREIGN KEY ("language_id") REFERENCES "languages" ("id") ON DELETE CASCADE;

ALTER TABLE "anime_metas" ADD FOREIGN KEY ("meta_id") REFERENCES "metas" ("id") ON DELETE CASCADE;
