// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.2
// source: v1/aspb/rpc_get_all_anime_series.proto

package aspbv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetAllAnimeSeriesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PageNumber int32  `protobuf:"varint,1,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	PageSize   int32  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Year       *int32 `protobuf:"varint,3,opt,name=year,proto3,oneof" json:"year,omitempty"`
}

func (x *GetAllAnimeSeriesRequest) Reset() {
	*x = GetAllAnimeSeriesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_aspb_rpc_get_all_anime_series_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllAnimeSeriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAnimeSeriesRequest) ProtoMessage() {}

func (x *GetAllAnimeSeriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_aspb_rpc_get_all_anime_series_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAnimeSeriesRequest.ProtoReflect.Descriptor instead.
func (*GetAllAnimeSeriesRequest) Descriptor() ([]byte, []int) {
	return file_v1_aspb_rpc_get_all_anime_series_proto_rawDescGZIP(), []int{0}
}

func (x *GetAllAnimeSeriesRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *GetAllAnimeSeriesRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *GetAllAnimeSeriesRequest) GetYear() int32 {
	if x != nil && x.Year != nil {
		return *x.Year
	}
	return 0
}

type GetAllAnimeSeriesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimeSeries []*AnimeSerieResponse `protobuf:"bytes,1,rep,name=animeSeries,proto3" json:"animeSeries,omitempty"`
}

func (x *GetAllAnimeSeriesResponse) Reset() {
	*x = GetAllAnimeSeriesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_v1_aspb_rpc_get_all_anime_series_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllAnimeSeriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllAnimeSeriesResponse) ProtoMessage() {}

func (x *GetAllAnimeSeriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_aspb_rpc_get_all_anime_series_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllAnimeSeriesResponse.ProtoReflect.Descriptor instead.
func (*GetAllAnimeSeriesResponse) Descriptor() ([]byte, []int) {
	return file_v1_aspb_rpc_get_all_anime_series_proto_rawDescGZIP(), []int{1}
}

func (x *GetAllAnimeSeriesResponse) GetAnimeSeries() []*AnimeSerieResponse {
	if x != nil {
		return x.AnimeSeries
	}
	return nil
}

var File_v1_aspb_rpc_get_all_anime_series_proto protoreflect.FileDescriptor

var file_v1_aspb_rpc_get_all_anime_series_proto_rawDesc = []byte{
	0x0a, 0x26, 0x76, 0x31, 0x2f, 0x61, 0x73, 0x70, 0x62, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65,
	0x74, 0x5f, 0x61, 0x6c, 0x6c, 0x5f, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x69,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x76, 0x31, 0x2e, 0x61, 0x73, 0x70,
	0x62, 0x76, 0x31, 0x1a, 0x1d, 0x76, 0x31, 0x2f, 0x61, 0x73, 0x70, 0x62, 0x2f, 0x6d, 0x73, 0x67,
	0x5f, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x69, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x78, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x6e, 0x69, 0x6d,
	0x65, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1e,
	0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x1a,
	0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x17, 0x0a, 0x04, 0x79, 0x65,
	0x61, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52, 0x04, 0x79, 0x65, 0x61, 0x72,
	0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x79, 0x65, 0x61, 0x72, 0x22, 0x5c, 0x0a, 0x19,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x69, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3f, 0x0a, 0x0b, 0x61, 0x6e, 0x69,
	0x6d, 0x65, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d,
	0x2e, 0x76, 0x31, 0x2e, 0x61, 0x73, 0x70, 0x62, 0x76, 0x31, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x65,
	0x53, 0x65, 0x72, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0b, 0x61,
	0x6e, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x69, 0x65, 0x73, 0x42, 0x35, 0x5a, 0x33, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6a, 0x2d, 0x79, 0x61, 0x63, 0x69,
	0x6e, 0x65, 0x2d, 0x66, 0x6c, 0x75, 0x74, 0x74, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x6a, 0x6f, 0x2f,
	0x70, 0x62, 0x2f, 0x76, 0x31, 0x2f, 0x61, 0x73, 0x70, 0x62, 0x3b, 0x61, 0x73, 0x70, 0x62, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_v1_aspb_rpc_get_all_anime_series_proto_rawDescOnce sync.Once
	file_v1_aspb_rpc_get_all_anime_series_proto_rawDescData = file_v1_aspb_rpc_get_all_anime_series_proto_rawDesc
)

func file_v1_aspb_rpc_get_all_anime_series_proto_rawDescGZIP() []byte {
	file_v1_aspb_rpc_get_all_anime_series_proto_rawDescOnce.Do(func() {
		file_v1_aspb_rpc_get_all_anime_series_proto_rawDescData = protoimpl.X.CompressGZIP(file_v1_aspb_rpc_get_all_anime_series_proto_rawDescData)
	})
	return file_v1_aspb_rpc_get_all_anime_series_proto_rawDescData
}

var file_v1_aspb_rpc_get_all_anime_series_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_v1_aspb_rpc_get_all_anime_series_proto_goTypes = []interface{}{
	(*GetAllAnimeSeriesRequest)(nil),  // 0: v1.aspbv1.GetAllAnimeSeriesRequest
	(*GetAllAnimeSeriesResponse)(nil), // 1: v1.aspbv1.GetAllAnimeSeriesResponse
	(*AnimeSerieResponse)(nil),        // 2: v1.aspbv1.AnimeSerieResponse
}
var file_v1_aspb_rpc_get_all_anime_series_proto_depIdxs = []int32{
	2, // 0: v1.aspbv1.GetAllAnimeSeriesResponse.animeSeries:type_name -> v1.aspbv1.AnimeSerieResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_v1_aspb_rpc_get_all_anime_series_proto_init() }
func file_v1_aspb_rpc_get_all_anime_series_proto_init() {
	if File_v1_aspb_rpc_get_all_anime_series_proto != nil {
		return
	}
	file_v1_aspb_msg_anime_serie_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_v1_aspb_rpc_get_all_anime_series_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllAnimeSeriesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_v1_aspb_rpc_get_all_anime_series_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllAnimeSeriesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_v1_aspb_rpc_get_all_anime_series_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_v1_aspb_rpc_get_all_anime_series_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_v1_aspb_rpc_get_all_anime_series_proto_goTypes,
		DependencyIndexes: file_v1_aspb_rpc_get_all_anime_series_proto_depIdxs,
		MessageInfos:      file_v1_aspb_rpc_get_all_anime_series_proto_msgTypes,
	}.Build()
	File_v1_aspb_rpc_get_all_anime_series_proto = out.File
	file_v1_aspb_rpc_get_all_anime_series_proto_rawDesc = nil
	file_v1_aspb_rpc_get_all_anime_series_proto_goTypes = nil
	file_v1_aspb_rpc_get_all_anime_series_proto_depIdxs = nil
}
