// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.24.4
// source: ampb/rpc_create_anime_movie_metas.proto

package ampb

import (
	nfpb "github.com/dj-yacine-flutter/gojo/pb/nfpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAnimeMovieMetasRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimeID    int64                    `protobuf:"varint,1,opt,name=animeID,proto3" json:"animeID,omitempty"`
	AnimeMetas []*nfpb.AnimeMetaRequest `protobuf:"bytes,2,rep,name=animeMetas,proto3" json:"animeMetas,omitempty"`
}

func (x *CreateAnimeMovieMetasRequest) Reset() {
	*x = CreateAnimeMovieMetasRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ampb_rpc_create_anime_movie_metas_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAnimeMovieMetasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnimeMovieMetasRequest) ProtoMessage() {}

func (x *CreateAnimeMovieMetasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ampb_rpc_create_anime_movie_metas_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnimeMovieMetasRequest.ProtoReflect.Descriptor instead.
func (*CreateAnimeMovieMetasRequest) Descriptor() ([]byte, []int) {
	return file_ampb_rpc_create_anime_movie_metas_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAnimeMovieMetasRequest) GetAnimeID() int64 {
	if x != nil {
		return x.AnimeID
	}
	return 0
}

func (x *CreateAnimeMovieMetasRequest) GetAnimeMetas() []*nfpb.AnimeMetaRequest {
	if x != nil {
		return x.AnimeMetas
	}
	return nil
}

type CreateAnimeMovieMetasResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimeID    int64                     `protobuf:"varint,1,opt,name=animeID,proto3" json:"animeID,omitempty"`
	AnimeMetas []*nfpb.AnimeMetaResponse `protobuf:"bytes,2,rep,name=animeMetas,proto3" json:"animeMetas,omitempty"`
}

func (x *CreateAnimeMovieMetasResponse) Reset() {
	*x = CreateAnimeMovieMetasResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ampb_rpc_create_anime_movie_metas_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAnimeMovieMetasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnimeMovieMetasResponse) ProtoMessage() {}

func (x *CreateAnimeMovieMetasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ampb_rpc_create_anime_movie_metas_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnimeMovieMetasResponse.ProtoReflect.Descriptor instead.
func (*CreateAnimeMovieMetasResponse) Descriptor() ([]byte, []int) {
	return file_ampb_rpc_create_anime_movie_metas_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAnimeMovieMetasResponse) GetAnimeID() int64 {
	if x != nil {
		return x.AnimeID
	}
	return 0
}

func (x *CreateAnimeMovieMetasResponse) GetAnimeMetas() []*nfpb.AnimeMetaResponse {
	if x != nil {
		return x.AnimeMetas
	}
	return nil
}

var File_ampb_rpc_create_anime_movie_metas_proto protoreflect.FileDescriptor

var file_ampb_rpc_create_anime_movie_metas_proto_rawDesc = []byte{
	0x0a, 0x27, 0x61, 0x6d, 0x70, 0x62, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x5f, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x6d, 0x65,
	0x74, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x6d, 0x70, 0x62, 0x1a,
	0x0f, 0x6e, 0x66, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x70, 0x0a, 0x1c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x4d,
	0x6f, 0x76, 0x69, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x36, 0x0a, 0x0a, 0x61, 0x6e,
	0x69, 0x6d, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x6e, 0x66, 0x70, 0x62, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0a, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x4d, 0x65, 0x74,
	0x61, 0x73, 0x22, 0x72, 0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d,
	0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x37, 0x0a,
	0x0a, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x6e, 0x66, 0x70, 0x62, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x4d, 0x65,
	0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0a, 0x61, 0x6e, 0x69, 0x6d,
	0x65, 0x4d, 0x65, 0x74, 0x61, 0x73, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6a, 0x2d, 0x79, 0x61, 0x63, 0x69, 0x6e, 0x65, 0x2d, 0x66,
	0x6c, 0x75, 0x74, 0x74, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x6a, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x61,
	0x6d, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ampb_rpc_create_anime_movie_metas_proto_rawDescOnce sync.Once
	file_ampb_rpc_create_anime_movie_metas_proto_rawDescData = file_ampb_rpc_create_anime_movie_metas_proto_rawDesc
)

func file_ampb_rpc_create_anime_movie_metas_proto_rawDescGZIP() []byte {
	file_ampb_rpc_create_anime_movie_metas_proto_rawDescOnce.Do(func() {
		file_ampb_rpc_create_anime_movie_metas_proto_rawDescData = protoimpl.X.CompressGZIP(file_ampb_rpc_create_anime_movie_metas_proto_rawDescData)
	})
	return file_ampb_rpc_create_anime_movie_metas_proto_rawDescData
}

var file_ampb_rpc_create_anime_movie_metas_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ampb_rpc_create_anime_movie_metas_proto_goTypes = []interface{}{
	(*CreateAnimeMovieMetasRequest)(nil),  // 0: ampb.CreateAnimeMovieMetasRequest
	(*CreateAnimeMovieMetasResponse)(nil), // 1: ampb.CreateAnimeMovieMetasResponse
	(*nfpb.AnimeMetaRequest)(nil),         // 2: nfpb.AnimeMetaRequest
	(*nfpb.AnimeMetaResponse)(nil),        // 3: nfpb.AnimeMetaResponse
}
var file_ampb_rpc_create_anime_movie_metas_proto_depIdxs = []int32{
	2, // 0: ampb.CreateAnimeMovieMetasRequest.animeMetas:type_name -> nfpb.AnimeMetaRequest
	3, // 1: ampb.CreateAnimeMovieMetasResponse.animeMetas:type_name -> nfpb.AnimeMetaResponse
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ampb_rpc_create_anime_movie_metas_proto_init() }
func file_ampb_rpc_create_anime_movie_metas_proto_init() {
	if File_ampb_rpc_create_anime_movie_metas_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ampb_rpc_create_anime_movie_metas_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAnimeMovieMetasRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ampb_rpc_create_anime_movie_metas_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAnimeMovieMetasResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ampb_rpc_create_anime_movie_metas_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ampb_rpc_create_anime_movie_metas_proto_goTypes,
		DependencyIndexes: file_ampb_rpc_create_anime_movie_metas_proto_depIdxs,
		MessageInfos:      file_ampb_rpc_create_anime_movie_metas_proto_msgTypes,
	}.Build()
	File_ampb_rpc_create_anime_movie_metas_proto = out.File
	file_ampb_rpc_create_anime_movie_metas_proto_rawDesc = nil
	file_ampb_rpc_create_anime_movie_metas_proto_goTypes = nil
	file_ampb_rpc_create_anime_movie_metas_proto_depIdxs = nil
}
