// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: ampb/rpc_create_anime_movie_title.proto

package ampb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAnimeMovieTitleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimeID     int64                   `protobuf:"varint,1,opt,name=animeID,proto3" json:"animeID,omitempty"`
	AnimeTitles *AnimeMovieTitleRequest `protobuf:"bytes,2,opt,name=animeTitles,proto3" json:"animeTitles,omitempty"`
}

func (x *CreateAnimeMovieTitleRequest) Reset() {
	*x = CreateAnimeMovieTitleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ampb_rpc_create_anime_movie_title_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAnimeMovieTitleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnimeMovieTitleRequest) ProtoMessage() {}

func (x *CreateAnimeMovieTitleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ampb_rpc_create_anime_movie_title_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnimeMovieTitleRequest.ProtoReflect.Descriptor instead.
func (*CreateAnimeMovieTitleRequest) Descriptor() ([]byte, []int) {
	return file_ampb_rpc_create_anime_movie_title_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAnimeMovieTitleRequest) GetAnimeID() int64 {
	if x != nil {
		return x.AnimeID
	}
	return 0
}

func (x *CreateAnimeMovieTitleRequest) GetAnimeTitles() *AnimeMovieTitleRequest {
	if x != nil {
		return x.AnimeTitles
	}
	return nil
}

type CreateAnimeMovieTitleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimeMovie  *AnimeMovieResponse      `protobuf:"bytes,1,opt,name=animeMovie,proto3" json:"animeMovie,omitempty"`
	AnimeTitles *AnimeMovieTitleResponse `protobuf:"bytes,2,opt,name=animeTitles,proto3" json:"animeTitles,omitempty"`
}

func (x *CreateAnimeMovieTitleResponse) Reset() {
	*x = CreateAnimeMovieTitleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ampb_rpc_create_anime_movie_title_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAnimeMovieTitleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnimeMovieTitleResponse) ProtoMessage() {}

func (x *CreateAnimeMovieTitleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ampb_rpc_create_anime_movie_title_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnimeMovieTitleResponse.ProtoReflect.Descriptor instead.
func (*CreateAnimeMovieTitleResponse) Descriptor() ([]byte, []int) {
	return file_ampb_rpc_create_anime_movie_title_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAnimeMovieTitleResponse) GetAnimeMovie() *AnimeMovieResponse {
	if x != nil {
		return x.AnimeMovie
	}
	return nil
}

func (x *CreateAnimeMovieTitleResponse) GetAnimeTitles() *AnimeMovieTitleResponse {
	if x != nil {
		return x.AnimeTitles
	}
	return nil
}

var File_ampb_rpc_create_anime_movie_title_proto protoreflect.FileDescriptor

var file_ampb_rpc_create_anime_movie_title_proto_rawDesc = []byte{
	0x0a, 0x27, 0x61, 0x6d, 0x70, 0x62, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x5f, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x6f, 0x76, 0x69, 0x65, 0x5f, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x6d, 0x70, 0x62, 0x1a,
	0x16, 0x61, 0x6d, 0x70, 0x62, 0x2f, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x5f, 0x6d, 0x6f, 0x76, 0x69,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x10, 0x61, 0x6d, 0x70, 0x62, 0x2f, 0x74, 0x69,
	0x74, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x78, 0x0a, 0x1c, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6e, 0x69,
	0x6d, 0x65, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x6e, 0x69, 0x6d,
	0x65, 0x49, 0x44, 0x12, 0x3e, 0x0a, 0x0b, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x54, 0x69, 0x74, 0x6c,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x6d, 0x70, 0x62, 0x2e,
	0x41, 0x6e, 0x69, 0x6d, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0b, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x54, 0x69, 0x74,
	0x6c, 0x65, 0x73, 0x22, 0x9a, 0x01, 0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6e,
	0x69, 0x6d, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x0a, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x4d, 0x6f,
	0x76, 0x69, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x61, 0x6d, 0x70, 0x62,
	0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x0a, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x12,
	0x3f, 0x0a, 0x0b, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x6d, 0x70, 0x62, 0x2e, 0x41, 0x6e, 0x69, 0x6d,
	0x65, 0x4d, 0x6f, 0x76, 0x69, 0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x0b, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x54, 0x69, 0x74, 0x6c, 0x65, 0x73,
	0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64,
	0x6a, 0x2d, 0x79, 0x61, 0x63, 0x69, 0x6e, 0x65, 0x2d, 0x66, 0x6c, 0x75, 0x74, 0x74, 0x65, 0x72,
	0x2f, 0x67, 0x6f, 0x6a, 0x6f, 0x2f, 0x70, 0x62, 0x2f, 0x61, 0x6d, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ampb_rpc_create_anime_movie_title_proto_rawDescOnce sync.Once
	file_ampb_rpc_create_anime_movie_title_proto_rawDescData = file_ampb_rpc_create_anime_movie_title_proto_rawDesc
)

func file_ampb_rpc_create_anime_movie_title_proto_rawDescGZIP() []byte {
	file_ampb_rpc_create_anime_movie_title_proto_rawDescOnce.Do(func() {
		file_ampb_rpc_create_anime_movie_title_proto_rawDescData = protoimpl.X.CompressGZIP(file_ampb_rpc_create_anime_movie_title_proto_rawDescData)
	})
	return file_ampb_rpc_create_anime_movie_title_proto_rawDescData
}

var file_ampb_rpc_create_anime_movie_title_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_ampb_rpc_create_anime_movie_title_proto_goTypes = []interface{}{
	(*CreateAnimeMovieTitleRequest)(nil),  // 0: ampb.CreateAnimeMovieTitleRequest
	(*CreateAnimeMovieTitleResponse)(nil), // 1: ampb.CreateAnimeMovieTitleResponse
	(*AnimeMovieTitleRequest)(nil),        // 2: ampb.AnimeMovieTitleRequest
	(*AnimeMovieResponse)(nil),            // 3: ampb.AnimeMovieResponse
	(*AnimeMovieTitleResponse)(nil),       // 4: ampb.AnimeMovieTitleResponse
}
var file_ampb_rpc_create_anime_movie_title_proto_depIdxs = []int32{
	2, // 0: ampb.CreateAnimeMovieTitleRequest.animeTitles:type_name -> ampb.AnimeMovieTitleRequest
	3, // 1: ampb.CreateAnimeMovieTitleResponse.animeMovie:type_name -> ampb.AnimeMovieResponse
	4, // 2: ampb.CreateAnimeMovieTitleResponse.animeTitles:type_name -> ampb.AnimeMovieTitleResponse
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ampb_rpc_create_anime_movie_title_proto_init() }
func file_ampb_rpc_create_anime_movie_title_proto_init() {
	if File_ampb_rpc_create_anime_movie_title_proto != nil {
		return
	}
	file_ampb_anime_movie_proto_init()
	file_ampb_title_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ampb_rpc_create_anime_movie_title_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAnimeMovieTitleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ampb_rpc_create_anime_movie_title_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAnimeMovieTitleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ampb_rpc_create_anime_movie_title_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ampb_rpc_create_anime_movie_title_proto_goTypes,
		DependencyIndexes: file_ampb_rpc_create_anime_movie_title_proto_depIdxs,
		MessageInfos:      file_ampb_rpc_create_anime_movie_title_proto_msgTypes,
	}.Build()
	File_ampb_rpc_create_anime_movie_title_proto = out.File
	file_ampb_rpc_create_anime_movie_title_proto_rawDesc = nil
	file_ampb_rpc_create_anime_movie_title_proto_goTypes = nil
	file_ampb_rpc_create_anime_movie_title_proto_depIdxs = nil
}
