// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: anime_movie_studio.sql

package db

import (
	"context"
)

const createAnimeMovieStudio = `-- name: CreateAnimeMovieStudio :one
INSERT INTO anime_movie_studios (anime_id, studio_id)
VALUES ($1, $2)
RETURNING id, anime_id, studio_id
`

type CreateAnimeMovieStudioParams struct {
	AnimeID  int64
	StudioID int32
}

func (q *Queries) CreateAnimeMovieStudio(ctx context.Context, arg CreateAnimeMovieStudioParams) (AnimeMovieStudio, error) {
	row := q.db.QueryRow(ctx, createAnimeMovieStudio, arg.AnimeID, arg.StudioID)
	var i AnimeMovieStudio
	err := row.Scan(&i.ID, &i.AnimeID, &i.StudioID)
	return i, err
}

const deleteAnimeMovieStudio = `-- name: DeleteAnimeMovieStudio :exec
DELETE FROM anime_movie_studios
WHERE anime_id = $1 AND studio_id = $2
`

type DeleteAnimeMovieStudioParams struct {
	AnimeID  int64
	StudioID int32
}

func (q *Queries) DeleteAnimeMovieStudio(ctx context.Context, arg DeleteAnimeMovieStudioParams) error {
	_, err := q.db.Exec(ctx, deleteAnimeMovieStudio, arg.AnimeID, arg.StudioID)
	return err
}

const getAnimeMovieStudio = `-- name: GetAnimeMovieStudio :one
SELECT id, anime_id, studio_id FROM anime_movie_studios
WHERE anime_id = $1 AND studio_id = $2
`

type GetAnimeMovieStudioParams struct {
	AnimeID  int64
	StudioID int32
}

func (q *Queries) GetAnimeMovieStudio(ctx context.Context, arg GetAnimeMovieStudioParams) (AnimeMovieStudio, error) {
	row := q.db.QueryRow(ctx, getAnimeMovieStudio, arg.AnimeID, arg.StudioID)
	var i AnimeMovieStudio
	err := row.Scan(&i.ID, &i.AnimeID, &i.StudioID)
	return i, err
}

const listAnimeMovieStudios = `-- name: ListAnimeMovieStudios :many
SELECT studio_id
FROM anime_movie_studios
WHERE anime_id = $1
ORDER BY id
`

func (q *Queries) ListAnimeMovieStudios(ctx context.Context, animeID int64) ([]int32, error) {
	rows, err := q.db.Query(ctx, listAnimeMovieStudios, animeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var studio_id int32
		if err := rows.Scan(&studio_id); err != nil {
			return nil, err
		}
		items = append(items, studio_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
