// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: anime_resource.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnimeResource = `-- name: CreateAnimeResource :one
INSERT INTO anime_resources (tmdb_id, imdb_id, official_website, wikipedia_url, crunchyroll_url, social_media)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING  id, tmdb_id, imdb_id, official_website, wikipedia_url, crunchyroll_url, social_media, created_at
`

type CreateAnimeResourceParams struct {
	TmdbID          int32
	ImdbID          string
	OfficialWebsite string
	WikipediaUrl    string
	CrunchyrollUrl  string
	SocialMedia     []string
}

func (q *Queries) CreateAnimeResource(ctx context.Context, arg CreateAnimeResourceParams) (AnimeResource, error) {
	row := q.db.QueryRow(ctx, createAnimeResource,
		arg.TmdbID,
		arg.ImdbID,
		arg.OfficialWebsite,
		arg.WikipediaUrl,
		arg.CrunchyrollUrl,
		arg.SocialMedia,
	)
	var i AnimeResource
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.ImdbID,
		&i.OfficialWebsite,
		&i.WikipediaUrl,
		&i.CrunchyrollUrl,
		&i.SocialMedia,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAnimeResource = `-- name: DeleteAnimeResource :exec
DELETE FROM anime_resources
WHERE id = $1
`

func (q *Queries) DeleteAnimeResource(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAnimeResource, id)
	return err
}

const getAnimeResource = `-- name: GetAnimeResource :one
SELECT id, tmdb_id, imdb_id, official_website, wikipedia_url, crunchyroll_url, social_media, created_at FROM anime_resources
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAnimeResource(ctx context.Context, id int64) (AnimeResource, error) {
	row := q.db.QueryRow(ctx, getAnimeResource, id)
	var i AnimeResource
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.ImdbID,
		&i.OfficialWebsite,
		&i.WikipediaUrl,
		&i.CrunchyrollUrl,
		&i.SocialMedia,
		&i.CreatedAt,
	)
	return i, err
}

const updateAnimeResource = `-- name: UpdateAnimeResource :one
UPDATE anime_resources
SET
  tmdb_id = COALESCE($1, tmdb_id),
  imdb_id = COALESCE($2, imdb_id),
  official_website = COALESCE($3, official_website),
  wikipedia_url = COALESCE($4, wikipedia_url),
  crunchyroll_url = COALESCE($5, crunchyroll_url),
  social_media = COALESCE($6, social_media)
WHERE
  id = $7
RETURNING id, tmdb_id, imdb_id, official_website, wikipedia_url, crunchyroll_url, social_media, created_at
`

type UpdateAnimeResourceParams struct {
	TmdbID          pgtype.Int4
	ImdbID          pgtype.Text
	OfficialWebsite pgtype.Text
	WikipediaUrl    pgtype.Text
	CrunchyrollUrl  pgtype.Text
	SocialMedia     []string
	ID              int64
}

func (q *Queries) UpdateAnimeResource(ctx context.Context, arg UpdateAnimeResourceParams) (AnimeResource, error) {
	row := q.db.QueryRow(ctx, updateAnimeResource,
		arg.TmdbID,
		arg.ImdbID,
		arg.OfficialWebsite,
		arg.WikipediaUrl,
		arg.CrunchyrollUrl,
		arg.SocialMedia,
		arg.ID,
	)
	var i AnimeResource
	err := row.Scan(
		&i.ID,
		&i.TmdbID,
		&i.ImdbID,
		&i.OfficialWebsite,
		&i.WikipediaUrl,
		&i.CrunchyrollUrl,
		&i.SocialMedia,
		&i.CreatedAt,
	)
	return i, err
}
