// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.23.0
// source: anime_serie_genre.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAnimeSerieGenre = `-- name: CreateAnimeSerieGenre :one
INSERT INTO anime_serie_genres (anime_id, genre_id)
VALUES ($1, $2)
RETURNING id, anime_id, genre_id
`

type CreateAnimeSerieGenreParams struct {
	AnimeID int64       `json:"anime_id"`
	GenreID pgtype.Int4 `json:"genre_id"`
}

func (q *Queries) CreateAnimeSerieGenre(ctx context.Context, arg CreateAnimeSerieGenreParams) (AnimeSerieGenre, error) {
	row := q.db.QueryRow(ctx, createAnimeSerieGenre, arg.AnimeID, arg.GenreID)
	var i AnimeSerieGenre
	err := row.Scan(&i.ID, &i.AnimeID, &i.GenreID)
	return i, err
}

const deleteAnimeSerieGenre = `-- name: DeleteAnimeSerieGenre :exec
DELETE FROM anime_serie_genres
WHERE anime_id = $1 AND genre_id = $2
`

type DeleteAnimeSerieGenreParams struct {
	AnimeID int64       `json:"anime_id"`
	GenreID pgtype.Int4 `json:"genre_id"`
}

func (q *Queries) DeleteAnimeSerieGenre(ctx context.Context, arg DeleteAnimeSerieGenreParams) error {
	_, err := q.db.Exec(ctx, deleteAnimeSerieGenre, arg.AnimeID, arg.GenreID)
	return err
}

const getAnimeSerieGenre = `-- name: GetAnimeSerieGenre :one
SELECT id, anime_id, genre_id FROM anime_serie_genres
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAnimeSerieGenre(ctx context.Context, id int64) (AnimeSerieGenre, error) {
	row := q.db.QueryRow(ctx, getAnimeSerieGenre, id)
	var i AnimeSerieGenre
	err := row.Scan(&i.ID, &i.AnimeID, &i.GenreID)
	return i, err
}

const listAnimeSerieGenres = `-- name: ListAnimeSerieGenres :many
SELECT genre_id
FROM anime_serie_genres
WHERE anime_id = $1
LIMIT $2
OFFSET $3
`

type ListAnimeSerieGenresParams struct {
	AnimeID int64 `json:"anime_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

func (q *Queries) ListAnimeSerieGenres(ctx context.Context, arg ListAnimeSerieGenresParams) ([]pgtype.Int4, error) {
	rows, err := q.db.Query(ctx, listAnimeSerieGenres, arg.AnimeID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Int4{}
	for rows.Next() {
		var genre_id pgtype.Int4
		if err := rows.Scan(&genre_id); err != nil {
			return nil, err
		}
		items = append(items, genre_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
