// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.22.0

package db

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type AnimeGenre struct {
	ID      int64       `json:"id"`
	AnimeID int64       `json:"anime_id"`
	GenreID pgtype.Int4 `json:"genre_id"`
}

type AnimeMeta struct {
	ID         int64 `json:"id"`
	AnimeID    int64 `json:"anime_id"`
	LanguageID int32 `json:"language_id"`
	MetaID     int64 `json:"meta_id"`
}

type AnimeMovie struct {
	ID            int64     `json:"id"`
	OriginalTitle string    `json:"original_title"`
	Aired         time.Time `json:"aired"`
	ReleaseYear   int32     `json:"release_year"`
	Duration      int32     `json:"duration"`
	CreatedAt     time.Time `json:"created_at"`
}

type AnimeStudio struct {
	ID       int64       `json:"id"`
	AnimeID  int64       `json:"anime_id"`
	StudioID pgtype.Int4 `json:"studio_id"`
}

type Genre struct {
	ID        int32     `json:"id"`
	GenreName string    `json:"genre_name"`
	CreatedAt time.Time `json:"created_at"`
}

type Language struct {
	ID           int32     `json:"id"`
	LanguageCode string    `json:"language_code"`
	LanguageName string    `json:"language_name"`
	CreatedAt    time.Time `json:"created_at"`
}

type Meta struct {
	ID        int64     `json:"id"`
	Title     string    `json:"title"`
	Overview  string    `json:"overview"`
	CreatedAt time.Time `json:"created_at"`
}

type Studio struct {
	ID         int32     `json:"id"`
	StudioName string    `json:"studio_name"`
	CreatedAt  time.Time `json:"created_at"`
}
