Project gojo {
  database_type: 'PostgreSQL'
  Note: '''
    # Gojo App Database
  '''
}

Table anime_movie {
  id bigserial [primary key, unique, increment, not null]
  original_title varchar [not null]
  aired timestamptz  [not null]
  release_year integer [not null]
  duration interval  [not null, default: `'00h 00m 00s'`]
  created_at timestamptz  [not null, default: `now()`]
    indexes {
      id
      original_title
      release_year
      (original_title, duration, aired) [unique]
    }
}

Table studios {
  id integer [primary key,unique, increment, not null]
  studio_name varchar [unique, not null]
  created_at timestamptz [not null, default: `now()`]
    indexes {
      id
      studio_name
    }
}

Table anime_studio {
  id bigserial [primary key, unique, increment, not null]
  anime_id bigserial [not null]
  studio_id integer [ref: > studios.id]
  indexes {
    anime_id
    studio_id
  }
}


Table genres {
  id integer [primary key, unique, increment, not null]
  genre_name varchar [unique, not null]
  created_at timestamptz [not null, default: `now()`]
    indexes {
      id
      genre_name
    }
}

Table anime_genre {
  id bigserial [primary key, unique, increment, not null]
  anime_id bigserial [not null]
  genre_id integer [ref: > genres.id]
  indexes {
    anime_id
    genre_id
  }
}

Table languages {
  id integer [primary key, unique, increment, not null]
  language_code varchar [unique, not null]
  language_name varchar [not null]
  created_at timestamptz [not null, default: `now()`]
    indexes {
      id
      language_code
    }
}

Table anime_metas {
  id bigserial [primary key, unique, increment, not null]
  anime_id bigserial [not null]
  language_id integer [not null]
  meta_id bigserial [not null]
    indexes {
      id
      (anime_id, language_id) [unique]
    }
}

Table metas {
  id bigserial [primary key, unique, increment, not null]
  title varchar [not null]
  overview varchar [not null]
  created_at timestamptz [not null, default: `now()`]
    indexes {
      id
      title
    }
}

Table users {
  id bigserial [pk, unique, increment, not null]
  role varchar [not null, default: 'member']
  username varchar [pk, unique, not null]
  email varchar [not null]
  hashed_password varchar [not null]
  is_email_verified bool [not null, default: false]
  full_name varchar [not null]
  password_changed_at timestamptz  [not null, default: `now()`]
  created_at timestamptz  [not null, default: `now()`]
    indexes {
      username
      full_name
    }
}

Table sessions {
  id uuid [pk]
  username varchar [not null]
  refresh_token varchar [not null]
  user_agent varchar [not null]
  client_ip varchar [not null]
  is_blocked boolean [not null, default: false]
  expires_at timestamptz [not null]
  created_at timestamptz [not null, default: `now()`]
}

Table verify_emails {
  id bigserial [pk]
  username varchar [not null]
  email varchar [not null]
  secret_code varchar [not null]
  is_used bool [not null, default: false]
  created_at timestamptz [not null, default: `now()`]
  expired_at timestamptz [not null, default: `now() + interval '15 minutes'`]
}


Ref {
  anime_movie.id - anime_metas.anime_id [delete: cascade]
}
Ref {
  anime_movie.id - anime_studio.anime_id [delete: cascade]
}
Ref {
  anime_movie.id - anime_genre.anime_id [delete: cascade]
}
Ref {
  languages.id - anime_metas.language_id [delete: cascade]
}
Ref {
  metas.id - anime_metas.meta_id [delete: cascade]
}
Ref {
  users.username - sessions.username [delete: cascade]
}
Ref {
  users.username - verify_emails.username [delete: cascade]
}