Project gojo {
  database_type: 'PostgreSQL'
  Note: '''
    # Gojo App Database
  '''
}

Table users {
  id bigserial [primary key, unique, increment, not null]
  role varchar [not null, default: 'member']
  username varchar [primary key, unique, not null]
  email varchar [not null]
  hashed_password varchar [not null]
  is_email_verified bool [not null, default: false]
  full_name varchar [not null]
  password_changed_at timestamptz  [not null, default: `now()`]
  created_at timestamptz  [not null, default: `now()`]
    indexes {
      username
      full_name
    }
}

Table sessions {
  id uuid [primary key, unique, not null]
  username varchar [not null]
  refresh_token varchar [not null]
  user_agent varchar [not null]
  client_ip varchar [not null]
  is_blocked boolean [not null, default: false]
  expires_at timestamptz [not null]
  created_at timestamptz [not null, default: `now()`]
    indexes {
      id
    }
}

Table verify_emails {
  id bigserial [primary key, unique, increment, not null]
  username varchar [not null]
  email varchar [not null]
  secret_code varchar [not null]
  is_used bool [not null, default: false]
  created_at timestamptz [not null, default: `now()`]
  expired_at timestamptz [not null, default: `now() + interval '15 minutes'`]
}

Table anime_movies {
  id bigserial [primary key, unique, increment, not null]
  original_title varchar [not null]
  aired timestamptz  [not null]
  release_year integer [not null]
  duration interval  [not null, default: `'00h 00m 00s'`]
  created_at timestamptz  [not null, default: `now()`]
    indexes {
      id
      original_title
      release_year
      (original_title, duration, aired) [unique]
    }
}

Table anime_series {
  id bigserial [primary key, unique, increment, not null]
  original_title varchar [not null]
  aired timestamptz  [not null]
  release_year integer [not null]
  duration interval  [not null, default: `'00h 00m 00s'`]
  created_at timestamptz  [not null, default: `now()`]
    indexes {
      id
      original_title
      release_year
      (original_title, duration, aired) [unique]
    }
}

Table languages {
  id integer [primary key, unique, increment, not null]
  language_code varchar [unique, not null]
  language_name varchar [not null]
  created_at timestamptz [not null, default: `now()`]
    indexes {
      id
      language_code
    }
}

Table studios {
  id integer [primary key,unique, increment, not null]
  studio_name varchar [unique, not null]
  created_at timestamptz [not null, default: `now()`]
    indexes {
      id
      studio_name
    }
}

Table genres {
  id integer [primary key, unique, increment, not null]
  genre_name varchar [unique, not null]
  created_at timestamptz [not null, default: `now()`]
    indexes {
      id
      genre_name
    }
}

Table metas {
  id bigserial [primary key, unique, increment, not null]
  title varchar [not null]
  overview varchar [not null]
  created_at timestamptz [not null, default: `now()`]
    indexes {
      id
      title
    }
}

Table anime_movie_studios {
  id bigserial [primary key, unique, increment, not null]
  anime_id bigserial [not null]
  studio_id integer [not null]
  indexes {
    anime_id
    studio_id
  }
}

Table anime_serie_studios {
  id bigserial [primary key, unique, increment, not null]
  anime_id bigserial [not null]
  studio_id integer [not null]
  indexes {
    anime_id
    studio_id
  }
}

Table anime_movie_genres {
  id bigserial [primary key, unique, increment, not null]
  anime_id bigserial [not null]
  genre_id integer [not null]
  indexes {
    anime_id
    genre_id
  }
}

Table anime_serie_genres {
  id bigserial [primary key, unique, increment, not null]
  anime_id bigserial [not null]
  genre_id integer [not null]
  indexes {
    anime_id
    genre_id
  }
}

Table anime_movie_metas {
  id bigserial [primary key, unique, increment, not null]
  anime_id bigserial [not null]
  language_id integer [not null]
  meta_id bigserial [not null]
    indexes {
      id
      (anime_id, language_id) [unique]
    }
}

Table anime_serie_metas {
  id bigserial [primary key, unique, increment, not null]
  anime_id bigserial [not null]
  language_id integer [not null]
  meta_id bigserial [not null]
    indexes {
      id
      (anime_id, language_id) [unique]
    }
}


Ref {
  users.username - sessions.username [delete: cascade]
}
Ref {
  users.username - verify_emails.username [delete: cascade]
}
Ref {
  anime_movies.id - anime_movie_metas.anime_id [delete: cascade]
}
Ref {
  anime_movies.id - anime_movie_studios.anime_id [delete: cascade]
}
Ref {
  anime_movies.id - anime_movie_genres.anime_id [delete: cascade]
}
Ref {
  anime_series.id - anime_serie_metas.anime_id [delete: cascade]
}
Ref {
  anime_series.id - anime_serie_studios.anime_id [delete: cascade]
}
Ref {
  anime_series.id - anime_serie_genres.anime_id [delete: cascade]
}
Ref {
  languages.id - anime_movie_metas.language_id [delete: cascade]
}
Ref {
  languages.id - anime_serie_metas.language_id [delete: cascade]
}
Ref {
  metas.id - anime_movie_metas.meta_id [delete: cascade]
}
Ref {
  metas.id - anime_serie_metas.meta_id [delete: cascade]
}
Ref {
  genres.id - anime_movie_genres.genre_id [delete: cascade]
}
Ref {
  genres.id - anime_serie_genres.genre_id [delete: cascade]
}
Ref {
  studios.id - anime_movie_studios.studio_id [delete: cascade]
}
Ref {
  studios.id - anime_serie_studios.studio_id [delete: cascade]
}