// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: aspb/rpc_create_anime_season.proto

package aspb

import (
	nfpb "github.com/dj-yacine-flutter/gojo/pb/nfpb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAnimeSeasonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Season      *AnimeSeasonRequest      `protobuf:"bytes,1,opt,name=season,proto3" json:"season,omitempty"`
	SeasonMetas []*nfpb.AnimeMetaRequest `protobuf:"bytes,2,rep,name=seasonMetas,proto3" json:"seasonMetas,omitempty"`
}

func (x *CreateAnimeSeasonRequest) Reset() {
	*x = CreateAnimeSeasonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspb_rpc_create_anime_season_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAnimeSeasonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnimeSeasonRequest) ProtoMessage() {}

func (x *CreateAnimeSeasonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aspb_rpc_create_anime_season_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnimeSeasonRequest.ProtoReflect.Descriptor instead.
func (*CreateAnimeSeasonRequest) Descriptor() ([]byte, []int) {
	return file_aspb_rpc_create_anime_season_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAnimeSeasonRequest) GetSeason() *AnimeSeasonRequest {
	if x != nil {
		return x.Season
	}
	return nil
}

func (x *CreateAnimeSeasonRequest) GetSeasonMetas() []*nfpb.AnimeMetaRequest {
	if x != nil {
		return x.SeasonMetas
	}
	return nil
}

type CreateAnimeSeasonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Season      *AnimeSeasonResponse      `protobuf:"bytes,1,opt,name=season,proto3" json:"season,omitempty"`
	SeasonMetas []*nfpb.AnimeMetaResponse `protobuf:"bytes,2,rep,name=seasonMetas,proto3" json:"seasonMetas,omitempty"`
}

func (x *CreateAnimeSeasonResponse) Reset() {
	*x = CreateAnimeSeasonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspb_rpc_create_anime_season_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAnimeSeasonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnimeSeasonResponse) ProtoMessage() {}

func (x *CreateAnimeSeasonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aspb_rpc_create_anime_season_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnimeSeasonResponse.ProtoReflect.Descriptor instead.
func (*CreateAnimeSeasonResponse) Descriptor() ([]byte, []int) {
	return file_aspb_rpc_create_anime_season_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAnimeSeasonResponse) GetSeason() *AnimeSeasonResponse {
	if x != nil {
		return x.Season
	}
	return nil
}

func (x *CreateAnimeSeasonResponse) GetSeasonMetas() []*nfpb.AnimeMetaResponse {
	if x != nil {
		return x.SeasonMetas
	}
	return nil
}

var File_aspb_rpc_create_anime_season_proto protoreflect.FileDescriptor

var file_aspb_rpc_create_anime_season_proto_rawDesc = []byte{
	0x0a, 0x22, 0x61, 0x73, 0x70, 0x62, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x5f, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x73, 0x70, 0x62, 0x1a, 0x17, 0x61, 0x73, 0x70, 0x62,
	0x2f, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x1a, 0x0f, 0x6e, 0x66, 0x70, 0x62, 0x2f, 0x6d, 0x65, 0x74, 0x61, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x86, 0x01, 0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x6e, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x61, 0x73, 0x70, 0x62, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x53, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x06, 0x73, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x12, 0x38, 0x0a, 0x0b, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x4d, 0x65, 0x74,
	0x61, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6e, 0x66, 0x70, 0x62, 0x2e,
	0x41, 0x6e, 0x69, 0x6d, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x52, 0x0b, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x73, 0x22, 0x89, 0x01,
	0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a, 0x06, 0x73,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x73,
	0x70, 0x62, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x06, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x39,
	0x0a, 0x0b, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6e, 0x66, 0x70, 0x62, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x65,
	0x4d, 0x65, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0b, 0x73, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x4d, 0x65, 0x74, 0x61, 0x73, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6a, 0x2d, 0x79, 0x61, 0x63, 0x69, 0x6e,
	0x65, 0x2d, 0x66, 0x6c, 0x75, 0x74, 0x74, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x6a, 0x6f, 0x2f, 0x70,
	0x62, 0x2f, 0x61, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aspb_rpc_create_anime_season_proto_rawDescOnce sync.Once
	file_aspb_rpc_create_anime_season_proto_rawDescData = file_aspb_rpc_create_anime_season_proto_rawDesc
)

func file_aspb_rpc_create_anime_season_proto_rawDescGZIP() []byte {
	file_aspb_rpc_create_anime_season_proto_rawDescOnce.Do(func() {
		file_aspb_rpc_create_anime_season_proto_rawDescData = protoimpl.X.CompressGZIP(file_aspb_rpc_create_anime_season_proto_rawDescData)
	})
	return file_aspb_rpc_create_anime_season_proto_rawDescData
}

var file_aspb_rpc_create_anime_season_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aspb_rpc_create_anime_season_proto_goTypes = []interface{}{
	(*CreateAnimeSeasonRequest)(nil),  // 0: aspb.CreateAnimeSeasonRequest
	(*CreateAnimeSeasonResponse)(nil), // 1: aspb.CreateAnimeSeasonResponse
	(*AnimeSeasonRequest)(nil),        // 2: aspb.AnimeSeasonRequest
	(*nfpb.AnimeMetaRequest)(nil),     // 3: nfpb.AnimeMetaRequest
	(*AnimeSeasonResponse)(nil),       // 4: aspb.AnimeSeasonResponse
	(*nfpb.AnimeMetaResponse)(nil),    // 5: nfpb.AnimeMetaResponse
}
var file_aspb_rpc_create_anime_season_proto_depIdxs = []int32{
	2, // 0: aspb.CreateAnimeSeasonRequest.season:type_name -> aspb.AnimeSeasonRequest
	3, // 1: aspb.CreateAnimeSeasonRequest.seasonMetas:type_name -> nfpb.AnimeMetaRequest
	4, // 2: aspb.CreateAnimeSeasonResponse.season:type_name -> aspb.AnimeSeasonResponse
	5, // 3: aspb.CreateAnimeSeasonResponse.seasonMetas:type_name -> nfpb.AnimeMetaResponse
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_aspb_rpc_create_anime_season_proto_init() }
func file_aspb_rpc_create_anime_season_proto_init() {
	if File_aspb_rpc_create_anime_season_proto != nil {
		return
	}
	file_aspb_anime_season_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_aspb_rpc_create_anime_season_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAnimeSeasonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspb_rpc_create_anime_season_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAnimeSeasonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aspb_rpc_create_anime_season_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aspb_rpc_create_anime_season_proto_goTypes,
		DependencyIndexes: file_aspb_rpc_create_anime_season_proto_depIdxs,
		MessageInfos:      file_aspb_rpc_create_anime_season_proto_msgTypes,
	}.Build()
	File_aspb_rpc_create_anime_season_proto = out.File
	file_aspb_rpc_create_anime_season_proto_rawDesc = nil
	file_aspb_rpc_create_anime_season_proto_goTypes = nil
	file_aspb_rpc_create_anime_season_proto_depIdxs = nil
}
