// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: aspb/rpc_query_anime_season.proto

package aspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryAnimeSeasonRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Query      string `protobuf:"bytes,1,opt,name=query,proto3" json:"query,omitempty"`
	PageNumber int32  `protobuf:"varint,2,opt,name=pageNumber,proto3" json:"pageNumber,omitempty"`
	PageSize   int32  `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
}

func (x *QueryAnimeSeasonRequest) Reset() {
	*x = QueryAnimeSeasonRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspb_rpc_query_anime_season_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryAnimeSeasonRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAnimeSeasonRequest) ProtoMessage() {}

func (x *QueryAnimeSeasonRequest) ProtoReflect() protoreflect.Message {
	mi := &file_aspb_rpc_query_anime_season_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAnimeSeasonRequest.ProtoReflect.Descriptor instead.
func (*QueryAnimeSeasonRequest) Descriptor() ([]byte, []int) {
	return file_aspb_rpc_query_anime_season_proto_rawDescGZIP(), []int{0}
}

func (x *QueryAnimeSeasonRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *QueryAnimeSeasonRequest) GetPageNumber() int32 {
	if x != nil {
		return x.PageNumber
	}
	return 0
}

func (x *QueryAnimeSeasonRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type QueryAnimeSeasonResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AnimeSeasons []*AnimeSeasonResponse `protobuf:"bytes,1,rep,name=animeSeasons,proto3" json:"animeSeasons,omitempty"`
}

func (x *QueryAnimeSeasonResponse) Reset() {
	*x = QueryAnimeSeasonResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_aspb_rpc_query_anime_season_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryAnimeSeasonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryAnimeSeasonResponse) ProtoMessage() {}

func (x *QueryAnimeSeasonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_aspb_rpc_query_anime_season_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryAnimeSeasonResponse.ProtoReflect.Descriptor instead.
func (*QueryAnimeSeasonResponse) Descriptor() ([]byte, []int) {
	return file_aspb_rpc_query_anime_season_proto_rawDescGZIP(), []int{1}
}

func (x *QueryAnimeSeasonResponse) GetAnimeSeasons() []*AnimeSeasonResponse {
	if x != nil {
		return x.AnimeSeasons
	}
	return nil
}

var File_aspb_rpc_query_anime_season_proto protoreflect.FileDescriptor

var file_aspb_rpc_query_anime_season_proto_rawDesc = []byte{
	0x0a, 0x21, 0x61, 0x73, 0x70, 0x62, 0x2f, 0x72, 0x70, 0x63, 0x5f, 0x71, 0x75, 0x65, 0x72, 0x79,
	0x5f, 0x61, 0x6e, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x04, 0x61, 0x73, 0x70, 0x62, 0x1a, 0x17, 0x61, 0x73, 0x70, 0x62, 0x2f,
	0x61, 0x6e, 0x69, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x22, 0x6b, 0x0a, 0x17, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x6e, 0x69, 0x6d, 0x65,
	0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a,
	0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71, 0x75,
	0x65, 0x72, 0x79, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x70, 0x61, 0x67, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22,
	0x59, 0x0a, 0x18, 0x51, 0x75, 0x65, 0x72, 0x79, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x61,
	0x73, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0c, 0x61,
	0x6e, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x19, 0x2e, 0x61, 0x73, 0x70, 0x62, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x65, 0x53, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52, 0x0c, 0x61, 0x6e,
	0x69, 0x6d, 0x65, 0x53, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x73, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x64, 0x6a, 0x2d, 0x79, 0x61, 0x63, 0x69,
	0x6e, 0x65, 0x2d, 0x66, 0x6c, 0x75, 0x74, 0x74, 0x65, 0x72, 0x2f, 0x67, 0x6f, 0x6a, 0x6f, 0x2f,
	0x70, 0x62, 0x2f, 0x61, 0x73, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_aspb_rpc_query_anime_season_proto_rawDescOnce sync.Once
	file_aspb_rpc_query_anime_season_proto_rawDescData = file_aspb_rpc_query_anime_season_proto_rawDesc
)

func file_aspb_rpc_query_anime_season_proto_rawDescGZIP() []byte {
	file_aspb_rpc_query_anime_season_proto_rawDescOnce.Do(func() {
		file_aspb_rpc_query_anime_season_proto_rawDescData = protoimpl.X.CompressGZIP(file_aspb_rpc_query_anime_season_proto_rawDescData)
	})
	return file_aspb_rpc_query_anime_season_proto_rawDescData
}

var file_aspb_rpc_query_anime_season_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_aspb_rpc_query_anime_season_proto_goTypes = []interface{}{
	(*QueryAnimeSeasonRequest)(nil),  // 0: aspb.QueryAnimeSeasonRequest
	(*QueryAnimeSeasonResponse)(nil), // 1: aspb.QueryAnimeSeasonResponse
	(*AnimeSeasonResponse)(nil),      // 2: aspb.AnimeSeasonResponse
}
var file_aspb_rpc_query_anime_season_proto_depIdxs = []int32{
	2, // 0: aspb.QueryAnimeSeasonResponse.animeSeasons:type_name -> aspb.AnimeSeasonResponse
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_aspb_rpc_query_anime_season_proto_init() }
func file_aspb_rpc_query_anime_season_proto_init() {
	if File_aspb_rpc_query_anime_season_proto != nil {
		return
	}
	file_aspb_anime_season_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_aspb_rpc_query_anime_season_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryAnimeSeasonRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_aspb_rpc_query_anime_season_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryAnimeSeasonResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_aspb_rpc_query_anime_season_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_aspb_rpc_query_anime_season_proto_goTypes,
		DependencyIndexes: file_aspb_rpc_query_anime_season_proto_depIdxs,
		MessageInfos:      file_aspb_rpc_query_anime_season_proto_msgTypes,
	}.Build()
	File_aspb_rpc_query_anime_season_proto = out.File
	file_aspb_rpc_query_anime_season_proto_rawDesc = nil
	file_aspb_rpc_query_anime_season_proto_goTypes = nil
	file_aspb_rpc_query_anime_season_proto_depIdxs = nil
}
